package desafios.fechas;

public class ZonasCopiar {

//	Zona horaria: Africa/Abidjan
//	Zona horaria: Africa/Accra
//	Zona horaria: Africa/Addis_Ababa
//	Zona horaria: Africa/Algiers
//	Zona horaria: Africa/Asmara
//	Zona horaria: Africa/Asmera
//	Zona horaria: Africa/Bamako
//	Zona horaria: Africa/Bangui
//	Zona horaria: Africa/Banjul
//	Zona horaria: Africa/Bissau
//	Zona horaria: Africa/Blantyre
//	Zona horaria: Africa/Brazzaville
//	Zona horaria: Africa/Bujumbura
//	Zona horaria: Africa/Cairo
//	Zona horaria: Africa/Casablanca
//	Zona horaria: Africa/Ceuta
//	Zona horaria: Africa/Conakry
//	Zona horaria: Africa/Dakar
//	Zona horaria: Africa/Dar_es_Salaam
//	Zona horaria: Africa/Djibouti
//	Zona horaria: Africa/Douala
//	Zona horaria: Africa/El_Aaiun
//	Zona horaria: Africa/Freetown
//	Zona horaria: Africa/Gaborone
//	Zona horaria: Africa/Harare
//	Zona horaria: Africa/Johannesburg
//	Zona horaria: Africa/Juba
//	Zona horaria: Africa/Kampala
//	Zona horaria: Africa/Khartoum
//	Zona horaria: Africa/Kigali
//	Zona horaria: Africa/Kinshasa
//	Zona horaria: Africa/Lagos
//	Zona horaria: Africa/Libreville
//	Zona horaria: Africa/Lome
//	Zona horaria: Africa/Luanda
//	Zona horaria: Africa/Lubumbashi
//	Zona horaria: Africa/Lusaka
//	Zona horaria: Africa/Malabo
//	Zona horaria: Africa/Maputo
//	Zona horaria: Africa/Maseru
//	Zona horaria: Africa/Mbabane
//	Zona horaria: Africa/Mogadishu
//	Zona horaria: Africa/Monrovia
//	Zona horaria: Africa/Nairobi
//	Zona horaria: Africa/Ndjamena
//	Zona horaria: Africa/Niamey
//	Zona horaria: Africa/Nouakchott
//	Zona horaria: Africa/Ouagadougou
//	Zona horaria: Africa/Porto-Novo
//	Zona horaria: Africa/Sao_Tome
//	Zona horaria: Africa/Timbuktu
//	Zona horaria: Africa/Tripoli
//	Zona horaria: Africa/Tunis
//	Zona horaria: Africa/Windhoek
//	Zona horaria: America/Adak
//	Zona horaria: America/Anchorage
//	Zona horaria: America/Anguilla
//	Zona horaria: America/Antigua
//	Zona horaria: America/Araguaina
//	Zona horaria: America/Argentina/Buenos_Aires
//	Zona horaria: America/Argentina/Catamarca
//	Zona horaria: America/Argentina/ComodRivadavia
//	Zona horaria: America/Argentina/Cordoba
//	Zona horaria: America/Argentina/Jujuy
//	Zona horaria: America/Argentina/La_Rioja
//	Zona horaria: America/Argentina/Mendoza
//	Zona horaria: America/Argentina/Rio_Gallegos
//	Zona horaria: America/Argentina/Salta
//	Zona horaria: America/Argentina/San_Juan
//	Zona horaria: America/Argentina/San_Luis
//	Zona horaria: America/Argentina/Tucuman
//	Zona horaria: America/Argentina/Ushuaia
//	Zona horaria: America/Aruba
//	Zona horaria: America/Asuncion
//	Zona horaria: America/Atikokan
//	Zona horaria: America/Atka
//	Zona horaria: America/Bahia
//	Zona horaria: America/Bahia_Banderas
//	Zona horaria: America/Barbados
//	Zona horaria: America/Belem
//	Zona horaria: America/Belize
//	Zona horaria: America/Blanc-Sablon
//	Zona horaria: America/Boa_Vista
//	Zona horaria: America/Bogota
//	Zona horaria: America/Boise
//	Zona horaria: America/Buenos_Aires
//	Zona horaria: America/Cambridge_Bay
//	Zona horaria: America/Campo_Grande
//	Zona horaria: America/Cancun
//	Zona horaria: America/Caracas
//	Zona horaria: America/Catamarca
//	Zona horaria: America/Cayenne
//	Zona horaria: America/Cayman
//	Zona horaria: America/Chicago
//	Zona horaria: America/Chihuahua
//	Zona horaria: America/Ciudad_Juarez
//	Zona horaria: America/Coral_Harbour
//	Zona horaria: America/Cordoba
//	Zona horaria: America/Costa_Rica
//	Zona horaria: America/Creston
//	Zona horaria: America/Cuiaba
//	Zona horaria: America/Curacao
//	Zona horaria: America/Danmarkshavn
//	Zona horaria: America/Dawson
//	Zona horaria: America/Dawson_Creek
//	Zona horaria: America/Denver
//	Zona horaria: America/Detroit
//	Zona horaria: America/Dominica
//	Zona horaria: America/Edmonton
//	Zona horaria: America/Eirunepe
//	Zona horaria: America/El_Salvador
//	Zona horaria: America/Ensenada
//	Zona horaria: America/Fort_Nelson
//	Zona horaria: America/Fort_Wayne
//	Zona horaria: America/Fortaleza
//	Zona horaria: America/Glace_Bay
//	Zona horaria: America/Godthab
//	Zona horaria: America/Goose_Bay
//	Zona horaria: America/Grand_Turk
//	Zona horaria: America/Grenada
//	Zona horaria: America/Guadeloupe
//	Zona horaria: America/Guatemala
//	Zona horaria: America/Guayaquil
//	Zona horaria: America/Guyana
//	Zona horaria: America/Halifax
//	Zona horaria: America/Havana
//	Zona horaria: America/Hermosillo
//	Zona horaria: America/Indiana/Indianapolis
//	Zona horaria: America/Indiana/Knox
//	Zona horaria: America/Indiana/Marengo
//	Zona horaria: America/Indiana/Petersburg
//	Zona horaria: America/Indiana/Tell_City
//	Zona horaria: America/Indiana/Vevay
//	Zona horaria: America/Indiana/Vincennes
//	Zona horaria: America/Indiana/Winamac
//	Zona horaria: America/Indianapolis
//	Zona horaria: America/Inuvik
//	Zona horaria: America/Iqaluit
//	Zona horaria: America/Jamaica
//	Zona horaria: America/Jujuy
//	Zona horaria: America/Juneau
//	Zona horaria: America/Kentucky/Louisville
//	Zona horaria: America/Kentucky/Monticello
//	Zona horaria: America/Knox_IN
//	Zona horaria: America/Kralendijk
//	Zona horaria: America/La_Paz
//	Zona horaria: America/Lima
//	Zona horaria: America/Los_Angeles
//	Zona horaria: America/Louisville
//	Zona horaria: America/Lower_Princes
//	Zona horaria: America/Maceio
//	Zona horaria: America/Managua
//	Zona horaria: America/Manaus
//	Zona horaria: America/Marigot
//	Zona horaria: America/Martinique
//	Zona horaria: America/Matamoros
//	Zona horaria: America/Mazatlan
//	Zona horaria: America/Mendoza
//	Zona horaria: America/Menominee
//	Zona horaria: America/Merida
//	Zona horaria: America/Metlakatla
//	Zona horaria: America/Mexico_City
//	Zona horaria: America/Miquelon
//	Zona horaria: America/Moncton
//	Zona horaria: America/Monterrey
//	Zona horaria: America/Montevideo
//	Zona horaria: America/Montreal
//	Zona horaria: America/Montserrat
//	Zona horaria: America/Nassau
//	Zona horaria: America/New_York
//	Zona horaria: America/Nipigon
//	Zona horaria: America/Nome
//	Zona horaria: America/Noronha
//	Zona horaria: America/North_Dakota/Beulah
//	Zona horaria: America/North_Dakota/Center
//	Zona horaria: America/North_Dakota/New_Salem
//	Zona horaria: America/Nuuk
//	Zona horaria: America/Ojinaga
//	Zona horaria: America/Panama
//	Zona horaria: America/Pangnirtung
//	Zona horaria: America/Paramaribo
//	Zona horaria: America/Phoenix
//	Zona horaria: America/Port-au-Prince
//	Zona horaria: America/Port_of_Spain
//	Zona horaria: America/Porto_Acre
//	Zona horaria: America/Porto_Velho
//	Zona horaria: America/Puerto_Rico
//	Zona horaria: America/Punta_Arenas
//	Zona horaria: America/Rainy_River
//	Zona horaria: America/Rankin_Inlet
//	Zona horaria: America/Recife
//	Zona horaria: America/Regina
//	Zona horaria: America/Resolute
//	Zona horaria: America/Rio_Branco
//	Zona horaria: America/Rosario
//	Zona horaria: America/Santa_Isabel
//	Zona horaria: America/Santarem
//	Zona horaria: America/Santiago
//	Zona horaria: America/Santo_Domingo
//	Zona horaria: America/Sao_Paulo
//	Zona horaria: America/Scoresbysund
//	Zona horaria: America/Shiprock
//	Zona horaria: America/Sitka
//	Zona horaria: America/St_Barthelemy
//	Zona horaria: America/St_Johns
//	Zona horaria: America/St_Kitts
//	Zona horaria: America/St_Lucia
//	Zona horaria: America/St_Thomas
//	Zona horaria: America/St_Vincent
//	Zona horaria: America/Swift_Current
//	Zona horaria: America/Tegucigalpa
//	Zona horaria: America/Thule
//	Zona horaria: America/Thunder_Bay
//	Zona horaria: America/Tijuana
//	Zona horaria: America/Toronto
//	Zona horaria: America/Tortola
//	Zona horaria: America/Vancouver
//	Zona horaria: America/Virgin
//	Zona horaria: America/Whitehorse
//	Zona horaria: America/Winnipeg
//	Zona horaria: America/Yakutat
//	Zona horaria: America/Yellowknife
//	Zona horaria: Antarctica/Casey
//	Zona horaria: Antarctica/Davis
//	Zona horaria: Antarctica/DumontDUrville
//	Zona horaria: Antarctica/Macquarie
//	Zona horaria: Antarctica/Mawson
//	Zona horaria: Antarctica/McMurdo
//	Zona horaria: Antarctica/Palmer
//	Zona horaria: Antarctica/Rothera
//	Zona horaria: Antarctica/South_Pole
//	Zona horaria: Antarctica/Syowa
//	Zona horaria: Antarctica/Troll
//	Zona horaria: Antarctica/Vostok
//	Zona horaria: Arctic/Longyearbyen
//	Zona horaria: Asia/Aden
//	Zona horaria: Asia/Almaty
//	Zona horaria: Asia/Amman
//	Zona horaria: Asia/Anadyr
//	Zona horaria: Asia/Aqtau
//	Zona horaria: Asia/Aqtobe
//	Zona horaria: Asia/Ashgabat
//	Zona horaria: Asia/Ashkhabad
//	Zona horaria: Asia/Atyrau
//	Zona horaria: Asia/Baghdad
//	Zona horaria: Asia/Bahrain
//	Zona horaria: Asia/Baku
//	Zona horaria: Asia/Bangkok
//	Zona horaria: Asia/Barnaul
//	Zona horaria: Asia/Beirut
//	Zona horaria: Asia/Bishkek
//	Zona horaria: Asia/Brunei
//	Zona horaria: Asia/Calcutta
//	Zona horaria: Asia/Chita
//	Zona horaria: Asia/Choibalsan
//	Zona horaria: Asia/Chongqing
//	Zona horaria: Asia/Chungking
//	Zona horaria: Asia/Colombo
//	Zona horaria: Asia/Dacca
//	Zona horaria: Asia/Damascus
//	Zona horaria: Asia/Dhaka
//	Zona horaria: Asia/Dili
//	Zona horaria: Asia/Dubai
//	Zona horaria: Asia/Dushanbe
//	Zona horaria: Asia/Famagusta
//	Zona horaria: Asia/Gaza
//	Zona horaria: Asia/Harbin
//	Zona horaria: Asia/Hebron
//	Zona horaria: Asia/Ho_Chi_Minh
//	Zona horaria: Asia/Hong_Kong
//	Zona horaria: Asia/Hovd
//	Zona horaria: Asia/Irkutsk
//	Zona horaria: Asia/Istanbul
//	Zona horaria: Asia/Jakarta
//	Zona horaria: Asia/Jayapura
//	Zona horaria: Asia/Jerusalem
//	Zona horaria: Asia/Kabul
//	Zona horaria: Asia/Kamchatka
//	Zona horaria: Asia/Karachi
//	Zona horaria: Asia/Kashgar
//	Zona horaria: Asia/Kathmandu
//	Zona horaria: Asia/Katmandu
//	Zona horaria: Asia/Khandyga
//	Zona horaria: Asia/Kolkata
//	Zona horaria: Asia/Krasnoyarsk
//	Zona horaria: Asia/Kuala_Lumpur
//	Zona horaria: Asia/Kuching
//	Zona horaria: Asia/Kuwait
//	Zona horaria: Asia/Macao
//	Zona horaria: Asia/Macau
//	Zona horaria: Asia/Magadan
//	Zona horaria: Asia/Makassar
//	Zona horaria: Asia/Manila
//	Zona horaria: Asia/Muscat
//	Zona horaria: Asia/Nicosia
//	Zona horaria: Asia/Novokuznetsk
//	Zona horaria: Asia/Novosibirsk
//	Zona horaria: Asia/Omsk
//	Zona horaria: Asia/Oral
//	Zona horaria: Asia/Phnom_Penh
//	Zona horaria: Asia/Pontianak
//	Zona horaria: Asia/Pyongyang
//	Zona horaria: Asia/Qatar
//	Zona horaria: Asia/Qostanay
//	Zona horaria: Asia/Qyzylorda
//	Zona horaria: Asia/Rangoon
//	Zona horaria: Asia/Riyadh
//	Zona horaria: Asia/Saigon
//	Zona horaria: Asia/Sakhalin
//	Zona horaria: Asia/Samarkand
//	Zona horaria: Asia/Seoul
//	Zona horaria: Asia/Shanghai
//	Zona horaria: Asia/Singapore
//	Zona horaria: Asia/Srednekolymsk
//	Zona horaria: Asia/Taipei
//	Zona horaria: Asia/Tashkent
//	Zona horaria: Asia/Tbilisi
//	Zona horaria: Asia/Tehran
//	Zona horaria: Asia/Tel_Aviv
//	Zona horaria: Asia/Thimbu
//	Zona horaria: Asia/Thimphu
//	Zona horaria: Asia/Tokyo
//	Zona horaria: Asia/Tomsk
//	Zona horaria: Asia/Ujung_Pandang
//	Zona horaria: Asia/Ulaanbaatar
//	Zona horaria: Asia/Ulan_Bator
//	Zona horaria: Asia/Urumqi
//	Zona horaria: Asia/Ust-Nera
//	Zona horaria: Asia/Vientiane
//	Zona horaria: Asia/Vladivostok
//	Zona horaria: Asia/Yakutsk
//	Zona horaria: Asia/Yangon
//	Zona horaria: Asia/Yekaterinburg
//	Zona horaria: Asia/Yerevan
//	Zona horaria: Atlantic/Azores
//	Zona horaria: Atlantic/Bermuda
//	Zona horaria: Atlantic/Canary
//	Zona horaria: Atlantic/Cape_Verde
//	Zona horaria: Atlantic/Faeroe
//	Zona horaria: Atlantic/Faroe
//	Zona horaria: Atlantic/Jan_Mayen
//	Zona horaria: Atlantic/Madeira
//	Zona horaria: Atlantic/Reykjavik
//	Zona horaria: Atlantic/South_Georgia
//	Zona horaria: Atlantic/St_Helena
//	Zona horaria: Atlantic/Stanley
//	Zona horaria: Australia/ACT
//	Zona horaria: Australia/Adelaide
//	Zona horaria: Australia/Brisbane
//	Zona horaria: Australia/Broken_Hill
//	Zona horaria: Australia/Canberra
//	Zona horaria: Australia/Currie
//	Zona horaria: Australia/Darwin
//	Zona horaria: Australia/Eucla
//	Zona horaria: Australia/Hobart
//	Zona horaria: Australia/LHI
//	Zona horaria: Australia/Lindeman
//	Zona horaria: Australia/Lord_Howe
//	Zona horaria: Australia/Melbourne
//	Zona horaria: Australia/NSW
//	Zona horaria: Australia/North
//	Zona horaria: Australia/Perth
//	Zona horaria: Australia/Queensland
//	Zona horaria: Australia/South
//	Zona horaria: Australia/Sydney
//	Zona horaria: Australia/Tasmania
//	Zona horaria: Australia/Victoria
//	Zona horaria: Australia/West
//	Zona horaria: Australia/Yancowinna
//	Zona horaria: Brazil/Acre
//	Zona horaria: Brazil/DeNoronha
//	Zona horaria: Brazil/East
//	Zona horaria: Brazil/West
//	Zona horaria: CET
//	Zona horaria: CST6CDT
//	Zona horaria: Canada/Atlantic
//	Zona horaria: Canada/Central
//	Zona horaria: Canada/Eastern
//	Zona horaria: Canada/Mountain
//	Zona horaria: Canada/Newfoundland
//	Zona horaria: Canada/Pacific
//	Zona horaria: Canada/Saskatchewan
//	Zona horaria: Canada/Yukon
//	Zona horaria: Chile/Continental
//	Zona horaria: Chile/EasterIsland
//	Zona horaria: Cuba
//	Zona horaria: EET
//	Zona horaria: EST5EDT
//	Zona horaria: Egypt
//	Zona horaria: Eire
//	Zona horaria: Etc/GMT
//	Zona horaria: Etc/GMT+0
//	Zona horaria: Etc/GMT+1
//	Zona horaria: Etc/GMT+10
//	Zona horaria: Etc/GMT+11
//	Zona horaria: Etc/GMT+12
//	Zona horaria: Etc/GMT+2
//	Zona horaria: Etc/GMT+3
//	Zona horaria: Etc/GMT+4
//	Zona horaria: Etc/GMT+5
//	Zona horaria: Etc/GMT+6
//	Zona horaria: Etc/GMT+7
//	Zona horaria: Etc/GMT+8
//	Zona horaria: Etc/GMT+9
//	Zona horaria: Etc/GMT-0
//	Zona horaria: Etc/GMT-1
//	Zona horaria: Etc/GMT-10
//	Zona horaria: Etc/GMT-11
//	Zona horaria: Etc/GMT-12
//	Zona horaria: Etc/GMT-13
//	Zona horaria: Etc/GMT-14
//	Zona horaria: Etc/GMT-2
//	Zona horaria: Etc/GMT-3
//	Zona horaria: Etc/GMT-4
//	Zona horaria: Etc/GMT-5
//	Zona horaria: Etc/GMT-6
//	Zona horaria: Etc/GMT-7
//	Zona horaria: Etc/GMT-8
//	Zona horaria: Etc/GMT-9
//	Zona horaria: Etc/GMT0
//	Zona horaria: Etc/Greenwich
//	Zona horaria: Etc/UCT
//	Zona horaria: Etc/UTC
//	Zona horaria: Etc/Universal
//	Zona horaria: Etc/Zulu
//	Zona horaria: Europe/Amsterdam
//	Zona horaria: Europe/Andorra
//	Zona horaria: Europe/Astrakhan
//	Zona horaria: Europe/Athens
//	Zona horaria: Europe/Belfast
//	Zona horaria: Europe/Belgrade
//	Zona horaria: Europe/Berlin
//	Zona horaria: Europe/Bratislava
//	Zona horaria: Europe/Brussels
//	Zona horaria: Europe/Bucharest
//	Zona horaria: Europe/Budapest
//	Zona horaria: Europe/Busingen
//	Zona horaria: Europe/Chisinau
//	Zona horaria: Europe/Copenhagen
//	Zona horaria: Europe/Dublin
//	Zona horaria: Europe/Gibraltar
//	Zona horaria: Europe/Guernsey
//	Zona horaria: Europe/Helsinki
//	Zona horaria: Europe/Isle_of_Man
//	Zona horaria: Europe/Istanbul
//	Zona horaria: Europe/Jersey
//	Zona horaria: Europe/Kaliningrad
//	Zona horaria: Europe/Kiev
//	Zona horaria: Europe/Kirov
//	Zona horaria: Europe/Kyiv
//	Zona horaria: Europe/Lisbon
//	Zona horaria: Europe/Ljubljana
//	Zona horaria: Europe/London
//	Zona horaria: Europe/Luxembourg
//	Zona horaria: Europe/Madrid
//	Zona horaria: Europe/Malta
//	Zona horaria: Europe/Mariehamn
//	Zona horaria: Europe/Minsk
//	Zona horaria: Europe/Monaco
//	Zona horaria: Europe/Moscow
//	Zona horaria: Europe/Nicosia
//	Zona horaria: Europe/Oslo
//	Zona horaria: Europe/Paris
//	Zona horaria: Europe/Podgorica
//	Zona horaria: Europe/Prague
//	Zona horaria: Europe/Riga
//	Zona horaria: Europe/Rome
//	Zona horaria: Europe/Samara
//	Zona horaria: Europe/San_Marino
//	Zona horaria: Europe/Sarajevo
//	Zona horaria: Europe/Saratov
//	Zona horaria: Europe/Simferopol
//	Zona horaria: Europe/Skopje
//	Zona horaria: Europe/Sofia
//	Zona horaria: Europe/Stockholm
//	Zona horaria: Europe/Tallinn
//	Zona horaria: Europe/Tirane
//	Zona horaria: Europe/Tiraspol
//	Zona horaria: Europe/Ulyanovsk
//	Zona horaria: Europe/Uzhgorod
//	Zona horaria: Europe/Vaduz
//	Zona horaria: Europe/Vatican
//	Zona horaria: Europe/Vienna
//	Zona horaria: Europe/Vilnius
//	Zona horaria: Europe/Volgograd
//	Zona horaria: Europe/Warsaw
//	Zona horaria: Europe/Zagreb
//	Zona horaria: Europe/Zaporozhye
//	Zona horaria: Europe/Zurich
//	Zona horaria: GB
//	Zona horaria: GB-Eire
//	Zona horaria: GMT
//	Zona horaria: GMT0
//	Zona horaria: Greenwich
//	Zona horaria: Hongkong
//	Zona horaria: Iceland
//	Zona horaria: Indian/Antananarivo
//	Zona horaria: Indian/Chagos
//	Zona horaria: Indian/Christmas
//	Zona horaria: Indian/Cocos
//	Zona horaria: Indian/Comoro
//	Zona horaria: Indian/Kerguelen
//	Zona horaria: Indian/Mahe
//	Zona horaria: Indian/Maldives
//	Zona horaria: Indian/Mauritius
//	Zona horaria: Indian/Mayotte
//	Zona horaria: Indian/Reunion
//	Zona horaria: Iran
//	Zona horaria: Israel
//	Zona horaria: Jamaica
//	Zona horaria: Japan
//	Zona horaria: Kwajalein
//	Zona horaria: Libya
//	Zona horaria: MET
//	Zona horaria: MST7MDT
//	Zona horaria: Mexico/BajaNorte
//	Zona horaria: Mexico/BajaSur
//	Zona horaria: Mexico/General
//	Zona horaria: NZ
//	Zona horaria: NZ-CHAT
//	Zona horaria: Navajo
//	Zona horaria: PRC
//	Zona horaria: PST8PDT
//	Zona horaria: Pacific/Apia
//	Zona horaria: Pacific/Auckland
//	Zona horaria: Pacific/Bougainville
//	Zona horaria: Pacific/Chatham
//	Zona horaria: Pacific/Chuuk
//	Zona horaria: Pacific/Easter
//	Zona horaria: Pacific/Efate
//	Zona horaria: Pacific/Enderbury
//	Zona horaria: Pacific/Fakaofo
//	Zona horaria: Pacific/Fiji
//	Zona horaria: Pacific/Funafuti
//	Zona horaria: Pacific/Galapagos
//	Zona horaria: Pacific/Gambier
//	Zona horaria: Pacific/Guadalcanal
//	Zona horaria: Pacific/Guam
//	Zona horaria: Pacific/Honolulu
//	Zona horaria: Pacific/Johnston
//	Zona horaria: Pacific/Kanton
//	Zona horaria: Pacific/Kiritimati
//	Zona horaria: Pacific/Kosrae
//	Zona horaria: Pacific/Kwajalein
//	Zona horaria: Pacific/Majuro
//	Zona horaria: Pacific/Marquesas
//	Zona horaria: Pacific/Midway
//	Zona horaria: Pacific/Nauru
//	Zona horaria: Pacific/Niue
//	Zona horaria: Pacific/Norfolk
//	Zona horaria: Pacific/Noumea
//	Zona horaria: Pacific/Pago_Pago
//	Zona horaria: Pacific/Palau
//	Zona horaria: Pacific/Pitcairn
//	Zona horaria: Pacific/Pohnpei
//	Zona horaria: Pacific/Ponape
//	Zona horaria: Pacific/Port_Moresby
//	Zona horaria: Pacific/Rarotonga
//	Zona horaria: Pacific/Saipan
//	Zona horaria: Pacific/Samoa
//	Zona horaria: Pacific/Tahiti
//	Zona horaria: Pacific/Tarawa
//	Zona horaria: Pacific/Tongatapu
//	Zona horaria: Pacific/Truk
//	Zona horaria: Pacific/Wake
//	Zona horaria: Pacific/Wallis
//	Zona horaria: Pacific/Yap
//	Zona horaria: Poland
//	Zona horaria: Portugal
//	Zona horaria: ROK
//	Zona horaria: Singapore
//	Zona horaria: SystemV/AST4
//	Zona horaria: SystemV/AST4ADT
//	Zona horaria: SystemV/CST6
//	Zona horaria: SystemV/CST6CDT
//	Zona horaria: SystemV/EST5
//	Zona horaria: SystemV/EST5EDT
//	Zona horaria: SystemV/HST10
//	Zona horaria: SystemV/MST7
//	Zona horaria: SystemV/MST7MDT
//	Zona horaria: SystemV/PST8
//	Zona horaria: SystemV/PST8PDT
//	Zona horaria: SystemV/YST9
//	Zona horaria: SystemV/YST9YDT
//	Zona horaria: Turkey
//	Zona horaria: UCT
//	Zona horaria: US/Alaska
//	Zona horaria: US/Aleutian
//	Zona horaria: US/Arizona
//	Zona horaria: US/Central
//	Zona horaria: US/East-Indiana
//	Zona horaria: US/Eastern
//	Zona horaria: US/Hawaii
//	Zona horaria: US/Indiana-Starke
//	Zona horaria: US/Michigan
//	Zona horaria: US/Mountain
//	Zona horaria: US/Pacific
//	Zona horaria: US/Samoa
//	Zona horaria: UTC
//	Zona horaria: Universal
//	Zona horaria: W-SU
//	Zona horaria: WET
//	Zona horaria: Zulu
//	Zona horaria: EST
//	Zona horaria: HST
//	Zona horaria: MST
//	Zona horaria: ACT
//	Zona horaria: AET
//	Zona horaria: AGT
//	Zona horaria: ART
//	Zona horaria: AST
//	Zona horaria: BET
//	Zona horaria: BST
//	Zona horaria: CAT
//	Zona horaria: CNT
//	Zona horaria: CST
//	Zona horaria: CTT
//	Zona horaria: EAT
//	Zona horaria: ECT
//	Zona horaria: IET
//	Zona horaria: IST
//	Zona horaria: JST
//	Zona horaria: MIT
//	Zona horaria: NET
//	Zona horaria: NST
//	Zona horaria: PLT
//	Zona horaria: PNT
//	Zona horaria: PRT
//	Zona horaria: PST
//	Zona horaria: SST
//	Zona horaria: VST

}
